### ISSUE TITLE
Google options data example results in NotImplementedError

### ISSUE THREAD

**Issue by BlackArbsCEO** [pydata/pandas-datareader#247]
Testing the options data example for Google Finance shown in the pandas_datareader read the docs results in a `NotImplementedError` shown below.

![screenshot from 2016-10-10 16-18-11](https://cloud.githubusercontent.com/assets/7452471/19253022/7da30936-8f05-11e6-91c2-5e85dc49c1d7.png)

**Comment by femtotrader** [comment]
Thanks @BlackArbsCEO 

I think you aren't using latest development version.
see https://github.com/pydata/pandas-datareader/issues/243

because now https://github.com/pydata/pandas-datareader/blob/master/pandas_datareader/data.py#L179
message is "currently only yahoo and google supported"

Closing but feel free to reopen if necessary
