### ISSUE TITLE
International market data - functionality addition request

### ISSUE THREAD

**Issue by CNuge** [pydata/pandas-datareader#408]
Hello,

I have developed a program to use google finance to scrape stock data for non-us markets (i.e. TSE, TYO, SSE). This functionality is currently not supported by pandas-datareader as far as I can tell and I am hoping to add a 'pandas_datareader.data.international_quotes()' function to this repository.

I would like to know if:
1. You are accepting additions of this kind
2. What sort of dependency limitations there are (i.e. my current build uses BeautifulSoup to read the html and I want to know if I should change this).

My current international stock scraping function can be found here:

https://github.com/CNuge/general_use_functions/blob/master/international_stock_scraper.py

Thanks for the feedback,
-Cam

**Comment by rsvp** [comment]
@CNuge hi, as you probably know, Google Finance is currently 
in its reconstruction period. 

Your proposed scrape code is not a robust solution (relative to API code) 
since page layouts are subject to whimsical UI changes. 
That said, it may be a good alternative if Google trashes its API 
since they have no intention of deprecating their Finance web pages.
