### ISSUE TITLE
MOEX: open, high, low - incorrect

### ISSUE THREAD

**Issue by Curious75** [pydata/pandas-datareader#748]
ticker = "MAGN" 2014-12-30
datareader extract other values than we can get from other resources

for example you can compare to MOEX-site: 
http://www.moex.com/ru/issue.aspx?board=TQBR&code=MAGN
LOW = Цена сделки минимальная | 10,061 (datareader = 8,8384)
HIGH = Цена сделки максимальная | 10,947 (datareader = 12,1528)
OPEN = Цена предторгового периода/Цена аукциона открытия | 10,947  (datareader = 12,1528)

CLOSE the same = Цена закрытия | 10,821 (datareader = 10,821)

you can also compare with https://www.finam.ru/profile/moex-akcii/mmk/export/?

**Comment by GreenArt11** [comment]
`pdr.DataReader('MAGN', 'moex', '2014-12-30', '2014-12-30')` returns 13 rows for the results in every of the 13 boards and trading modes.

You should use only rows with the link to `TQBR` board due to it is the main board of this ticker (as it is shown there: `https://iss.moex.com/iss/securities/MGNT`)

Made an improvement issue #811

**Comment by GreenArt11** [comment]
fixed by #812
